#!/bin/bash

awk 'BEGIN{FS="\n";RS="************END************";ukEntries=0;errors=0}
{
	if ($0~/unknown/){
		print $0;ukEntries+=1
	}
	if ($0~/ERROR/){
		print $0;errors+=1
	}
}
END{
	print "There are " ukEntries " out of " NR " (" 100*(ukEntries/NR)"%) with entries unknown"
	print "There are " errors " out of " NR " (" 100*(errors/NR)"%) with errors"

}' $1
